export const subjects = [
  { id: "marathi", name: "Marathi", nameMr: "मराठी" },
  { id: "english", name: "English", nameMr: "इंग्रजी" },
  { id: "math", name: "Mathematics", nameMr: "गणित" },
  { id: "reasoning", name: "Reasoning", nameMr: "बुद्धिमत्ता" },
  { id: "gk", name: "General Knowledge", nameMr: "सामान्य ज्ञान" },
  { id: "current", name: "Current Affairs", nameMr: "चालू घडामोडी" },
  { id: "history", name: "History", nameMr: "इतिहास" },
  { id: "geography", name: "Geography", nameMr: "भूगोल" },
  { id: "constitution", name: "Indian Constitution", nameMr: "भारतीय राज्यघटना" },
  { id: "science", name: "Science", nameMr: "विज्ञान" },
];

export const questions = [
  {
    id: 1,
    subject: "constitution",
    text: "When did the Constitution of India come into effect?",
    textMr: "भारताचे संविधान कधी लागू झाले?",
    options: ["15 August 1947", "26 January 1950", "26 November 1949", "2 October 1950"],
    correct: 1,
    explanation: "The Constitution came into force on 26 January 1950.",
  },
  {
    id: 2,
    subject: "math",
    text: "What is 20% of 250?",
    textMr: "250 चे 20% किती?",
    options: ["25", "40", "50", "60"],
    correct: 2,
    explanation: "250 × 20 / 100 = 50.",
  },
  {
    id: 3,
    subject: "reasoning",
    text: "Find the next number: 2, 4, 8, 16, ?",
    textMr: "पुढील संख्या शोधा: 2, 4, 8, 16, ?",
    options: ["20", "24", "30", "32"],
    correct: 3,
    explanation: "Each number is multiplied by 2.",
  },
  {
    id: 4,
    subject: "history",
    text: "Who founded the Maratha Empire?",
    textMr: "मराठा साम्राज्याची स्थापना कोणी केली?",
    options: ["Chhatrapati Shivaji Maharaj", "Sambhaji Maharaj", "Bajirao I", "Rajaram Maharaj"],
    correct: 0,
    explanation: "Chhatrapati Shivaji Maharaj established the Maratha state.",
  },
  {
    id: 5,
    subject: "geography",
    text: "Which is the longest river in Maharashtra?",
    textMr: "महाराष्ट्रातील सर्वात लांब नदी कोणती?",
    options: ["Godavari", "Krishna", "Bhima", "Tapi"],
    correct: 0,
    explanation: "The Godavari is the longest river flowing through Maharashtra.",
  },
  {
    id: 6,
    subject: "science",
    text: "Which gas is essential for human respiration?",
    textMr: "मानवी श्वसनासाठी कोणता वायू आवश्यक आहे?",
    options: ["Nitrogen", "Oxygen", "Carbon dioxide", "Hydrogen"],
    correct: 1,
    explanation: "Oxygen is required for aerobic respiration.",
  },
  {
    id: 7,
    subject: "marathi",
    text: "मराठी भाषेची लिपी कोणती आहे?",
    textMr: "मराठी भाषेची लिपी कोणती आहे?",
    options: ["देवनागरी", "रोमन", "गुरुमुखी", "उर्दू"],
    correct: 0,
    explanation: "Marathi is primarily written in the Devanagari script.",
  },
  {
    id: 8,
    subject: "english",
    text: "Choose the synonym of 'Rapid'.",
    textMr: "‘Rapid’ या शब्दाचा समानार्थी शब्द निवडा.",
    options: ["Slow", "Fast", "Weak", "Late"],
    correct: 1,
    explanation: "Rapid means fast or quick.",
  },
  {
    id: 9,
    subject: "gk",
    text: "What is the capital of Maharashtra?",
    textMr: "महाराष्ट्राची राजधानी कोणती?",
    options: ["Pune", "Nagpur", "Mumbai", "Nashik"],
    correct: 2,
    explanation: "Mumbai is the capital of Maharashtra.",
  },
  {
    id: 10,
    subject: "current",
    text: "Which body conducts the UPSC Civil Services Examination?",
    textMr: "UPSC नागरी सेवा परीक्षा कोणती संस्था घेते?",
    options: ["UPSC", "SSC", "MPSC", "IBPS"],
    correct: 0,
    explanation: "The Union Public Service Commission conducts the Civil Services Examination.",
  },
];

export const exams = [
  {
    id: "police-01",
    title: "Police Bharti Mock Test 01",
    type: "Police Bharti",
    questions: 50,
    marks: 50,
    duration: 45,
    negative: 0.25,
    difficulty: "Medium",
    price: 0,
    status: "LIVE",
    language: "Marathi + English",
  },
  {
    id: "police-weekly",
    title: "Police Bharti Weekly Test #12",
    type: "Police Bharti",
    questions: 100,
    marks: 100,
    duration: 90,
    negative: 0.25,
    difficulty: "Hard",
    price: 49,
    status: "SCHEDULED",
    language: "Marathi + English",
  },
  {
    id: "mpsc-01",
    title: "MPSC Foundation Mock Test",
    type: "MPSC",
    questions: 100,
    marks: 100,
    duration: 120,
    negative: 0.25,
    difficulty: "Hard",
    price: 99,
    status: "AVAILABLE",
    language: "Marathi + English",
  },
  {
    id: "saralseva-01",
    title: "Saralseva Practice Test",
    type: "Saralseva",
    questions: 50,
    marks: 50,
    duration: 45,
    negative: 0.25,
    difficulty: "Medium",
    price: 49,
    status: "AVAILABLE",
    language: "Marathi + English",
  },
];

export const leaderboard = [
  ["Amit Patil", 94, "95%"],
  ["Sneha Jadhav", 91, "91%"],
  ["Rahul Shinde", 89, "89%"],
  ["Pooja More", 87, "87%"],
  ["Akshay Pawar", 84, "84%"],
];
